version: '3.8'
services:
  pgdatabase:
    container_name: postgres_db
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes: 
      - ./scrapers:/var/lib/postgres/data/ny_taxi
    ports: 
      - '5432:5432'
    networks:
      - goral_data_eng
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports: 
      - '8080:80'
    networks:
      - goral_data_eng
  sensor_1:
    container_name: sensor_1
    build:
      context: ./sensor_1
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - '5000:5000'
    networks:
      - goral_data_eng
    volumes:
      - ./sensor_1:/code
    depends_on:
      - mqtt
  # sensor_2:
  #   container_name: sensor_2
  #   build:
  #     context: ./sensor_2
  #     dockerfile: Dockerfile
  #   environment:
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - '5001:5001'
  #   networks:
  #     - goral_data_eng
  #   volumes:
  #     - ./sensor_2:/code
  #   depends_on:
  #     - mqtt
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes: 
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquito/data
      - ./mosquitto/log:/mosquito/log
    networks:
      - goral_data_eng
    expose:
      - 1883
    ports:
    - '1883:1883'
    - '9001:9001'

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  goral_data_eng:
    driver: bridge
